return {
  opt = {
    tabstop = 2,
    shiftwidth = 2,
    softtabstop = 2,
    relativenumber = true,
    number = true,
    signcolumn = "auto",
    colorcolumn = "80,120",
    mouse = "",
    spell = true,
    spelllang = { "en_us" },
    guifont = "Hack Nerd Font Mono:h12",
    wrap = false,
  },
  g = {
    mapleader = " ",
    autoformat_enabled = true,
    cmp_enabled = true,
    autopairs_enabled = true,
    diagnostics_enabled = true,
    status_diagnostics_enabled = true,
    icons_enabled = true,
    ui_notifications_enabled = true,
    neovide_cursor_animation_length = 0.05,
  },
}
